name: TrollTouchAgent
options:
  bundleIdPrefix: com.trolltouch
  deploymentTarget:
    iOS: 14.0

targets:
  TrollTouchAgent:
    type: application
    platform: iOS
    sources:
      - TrollTouchAgent/AppDelegate.h
      - TrollTouchAgent/AppDelegate.m
      - TrollTouchAgent/main.m
      - TrollTouchAgent/AgentServer.h
      - TrollTouchAgent/AgentServer.m
      - TrollTouchAgent/TouchInjector.h
      - TrollTouchAgent/TouchInjector.m
      - TrollTouchAgent/SharedCommandQueue.h
      - TrollTouchAgent/SharedCommandQueue.m
      - TrollTouchAgent/AgentSelfTest.h
      - TrollTouchAgent/AgentSelfTest.m
      - TrollTouchAgent/FileLogger.h
      - TrollTouchAgent/FileLogger.m
      - TrollTouchAgent/Info.plist
    settings:
      PRODUCT_NAME: TrollTouchAgent
      PRODUCT_BUNDLE_IDENTIFIER: com.trolltouch.agent
      INFOPLIST_FILE: TrollTouchAgent/Info.plist
      IPHONEOS_DEPLOYMENT_TARGET: 14.0
      TARGETED_DEVICE_FAMILY: "1,2"
      ENABLE_BITCODE: NO
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGN_IDENTITY: ""
      CODE_SIGN_ENTITLEMENTS: TrollTouchAgent/TrollTouchAgent.entitlements
      OTHER_LDFLAGS:
        - "-framework"
        - "UIKit"
        - "-framework"
        - "Foundation"
        - "-framework"
        - "CoreGraphics"
